In [9]:
from market_analysis.data.providers import NSEClient, YahooClient

from market_analysis.database.models.enums import Exchange
from market_analysis.database.models import Security
from market_analysis.database import SessionLocal

In [2]:
client = NSEClient()

In [3]:
df = client.fetch_symbols()

In [4]:
df.describe()

       paid_up_value   market_lot  face_value
count         2397.0  2397.000000      2397.0
mean        6.418023     1.123488    6.418023
std        20.703358     3.189052   20.703358
min              1.0     1.000000         1.0
25%              2.0     1.000000         2.0
50%              5.0     1.000000         5.0
75%             10.0     1.000000        10.0
max           1000.0   100.000000      1000.0

In [5]:
df.dtypes

symbol               str
name                 str
series               str
listing_date      object
paid_up_value    Float64
market_lot         int64
isin                 str
face_value       Float64
exchange             str
security_type        str
currency             str
active              bool
dtype: object

In [7]:
with SessionLocal() as session:

    security = (
        session.query(Security)
        .filter(
            Security.symbol == "RELIANCE",
            Security.exchange == Exchange.NSE,
        )
        .first()
    )

In [8]:
security

Security(id=1732, symbol='RELIANCE', exchange='NSE', type='STOCK', isin='INE002A01018')

In [10]:
yh_client = YahooClient()

In [11]:
df = yh_client.fetch_daily_history(security)

In [12]:
df

Price,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2026-07-06,1321.300049,1321.300049,1325.599976,1299.400024,1304.000000,7610709
2026-07-07,1308.400024,1308.400024,1328.000000,1304.099976,1323.500000,14335554
2026-07-08,1275.900024,1275.900024,1302.300049,1271.599976,1297.000000,19960868
2026-07-09,1279.800049,1279.800049,1296.500000,1274.199951,1277.099976,14651963
2026-07-10,1307.800049,1307.800049,1311.099976,1287.800049,1291.900024,8412537
2026-07-13,1296.900024,1296.900024,1306.400024,1295.000000,1300.000000,9488352
2026-07-14,1293.000000,1293.000000,1308.000000,1286.900024,1290.000000,13511284
2026-07-15,1295.500000,1295.500000,1310.900024,1294.099976,1294.099976,9577965
2026-07-16,1296.599976,1296.599976,1309.400024,1291.800049,1295.500000,15631046
2026-07-17,1327.199951,1327.199951,1330.300049,1296.099976,1300.000000,18302218
2026-07-20,1323.099976,1323.099976,1345.900024,1314.900024,1317.199951,14305844
2026-07-21,1303.699951,1303.699951,1326.900024,1302.699951,1321.000000,12753410
2026-07-22,1288.599976,1288.599976,1304.599976,1280.699951,1302.000000,10840383
2026-07-23,1272.199951,1272.199951,1287.300049,1268.000000,1283.000000,12580741
2026-07-24,1278.000000,1278.000000,1283.400024,1249.800049,1265.000000,9817000
2026-07-27,1280.000000,1280.000000,1288.699951,1278.000000,1288.199951,7163132
2026-07-28,1267.699951,1267.699951,1279.199951,1265.900024,1275.000000,9312184
2026-07-29,1275.900024,1275.900024,1282.400024,1268.699951,1275.000000,9448307
2026-07-30,1292.900024,1292.900024,1297.000000,1275.300049,1279.800049,12158451
2026-07-31,1307.800049,1307.800049,1309.699951,1293.599976,1295.000000,8624996
2026-08-03,1319.000000,1319.000000,1319.000000,1306.000000,1315.199951,7508023
2026-08-04,1290.900024,1290.900024,1315.000000,1286.400024,1315.000000,10759546
2026-08-05,1280.000000,1280.000000,1299.000000,1270.099976,1293.000000,24820782
2026-08-06,1325.000000,1325.000000,1325.199951,1281.199951,1285.000000,20203425